version: '3'
services:
  webpack:
    image: node:16
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "yarn install && yarn run start"
    ports:
      - "8080:8080"

